source 'https://github.com/CocoaPods/Specs.git'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
use_frameworks!

platform :ios, '9.0'
workspace 'Example'

target 'Embedded' do
    project 'Embedded.xcodeproj'
    #pod 'paymentSDK/All', :path => '..'	
    pod 'paymentSDK/All', '~> 3.5.0'
end

target 'Simple' do
    project 'Simple.xcodeproj'
    #pod 'paymentSDK/All', :path => '..'     
    pod 'paymentSDK/All', '~> 3.5.0'
end




