//
//  WDSEPAPayment.h
//  WDeCom
//
//  Created by Sedlak, Stefan on 10/12/15.
//  Copyright © 2018 Wirecard Technologies GmbH. All rights reserved.
//

#import <WDeCom/WDeCom.h>

/** @addtogroup ios_sdk
 *  @{
 */

/**
 * @brief Defines SEPA payment method.
 */
@interface WDECSEPAPayment : WDECPayment

/**
 @brief Setting this value to WDECBoolYes means services and products are only available to businesses, the payer cannot be a private individual.
 @details It is optional.
 */
@property (assign, nonatomic) WDECBool B2B;

/**
 @brief The Creditor Id for the Merchant Account SEPA.
 @details It is mandatory.
 */
@property (strong, nonatomic, nonnull ) NSString *creditorID;

/**
 @brief The Mandate Id for the Mandate Transaction, generated by merchant.
 */
@property (strong, nonatomic, nonnull ) NSString *mandateID;
/**
 @brief The date that the Mandate was signed.
 @details It is optional. If value is nil, current date will be used.
 */
@property (strong, nonatomic, nullable) NSDate *mandateSignedDate;

/**
 @brief The date that the Mandate Transaction is due
 */
@property (strong, nonatomic, nullable) NSDate *dueDate;

/**
 @brief It describes recurring transactions.
 */
@property (strong, nonatomic, nullable) WDECPeriodic *periodic;

@end

/** @} */
